// Runs the Fortran kernel headless, as WebAssembly and as the wasm2js
// fallback, and checks the two agree for every scene.
// Usage: node tools/selftest.mjs
import fs from 'fs'; import vm from 'vm'; import path from 'path'; import url from 'url';
const R = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');

// LFortran imports libm as env._lfortran_dXXX (and fma from contraction):
// satisfy any of them from Math.
const env = new Proxy({}, {
  has: () => true,
  get(_, k) {
    if (k === 'fma') return (a, b, c) => a * b + c;
    if (k === 'pow') return Math.pow;
    const m = /^_lfortran_d?(\w+?)$/.exec(String(k));
    if (m && typeof Math[m[1]] === 'function') return Math[m[1]];
    throw new Error('selftest: no provider for import env.' + String(k));
  },
});
const wasm = fs.readFileSync(path.join(R, 'build/view.opt.wasm'));
const mod = await WebAssembly.compile(wasm);
const imports = {};
for (const im of WebAssembly.Module.imports(mod)) imports[im.name] = env[im.name];
const W = (await WebAssembly.instantiate(mod, { env: imports })).exports;
const ctx = {}; vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(R, 'build/fallback.js'), 'utf8'), ctx);
const F = ctx.VIEW1108_ASM(imports);

const f64 = (K, name, n) => Array.from(new Float64Array(K.memory.buffer, K[name].value, n));
const i32 = (K, name) => new Int32Array(K.memory.buffer, K[name].value, 1)[0];
function run(K, scene, flags = 3, view = 0, target = 0, lablv = 0, get = null) {
  K.view_init(scene);
  new Int32Array(K.memory.buffer, K.in_flags.value, 1)[0] = flags;
  if (K.in_view) {
    new Int32Array(K.memory.buffer, K.in_view.value, 1)[0] = view;
    new Int32Array(K.memory.buffer, K.in_target.value, 1)[0] = target;
  }
  if (K.in_lablv) new Int32Array(K.memory.buffer, K.in_lablv.value, 1)[0] = lablv;
  if (get !== null) new Float64Array(K.memory.buffer, K.in_get.value, 1)[0] = get;
  K.view_frame();
  const nvec = i32(K, 'nvec'), nstar = i32(K, 'nstar'), nlab = i32(K, 'nlab');
  const ntxt = i32(K, 'ntxt'), nchr = i32(K, 'nchr');
  return { nvec, nstar, nlab, ntxt, hdr: f64(K, 'hdr', 24), vbuf: f64(K, 'vbuf', 5 * nvec),
           lbuf: f64(K, 'lbuf', 4 * nlab),
           tbuf: f64(K, 'tbuf', 4 * ntxt),
           tchr: Array.from(new Int32Array(K.memory.buffer, K.tchr.value, nchr)),
           init: f64(K, 'in_get', 1)[0] };
}
// The situations (scene = situation id) and their scenarios, generated by tools/gen_data.py from the SITUATION cards
// into build/names.js, the page's copy: the cases below pick situations by what their cards say, not by number.
const NAMES = vm.runInNewContext(fs.readFileSync(path.join(R, 'build/names.js'), 'utf8') + '\nVIEW_NAMES');
const SIT = NAMES.SITUATIONS, SCNS = NAMES.SCENARIOS;
const SCENES = SIT.map(s => s.id), SCN = Object.fromEntries(SIT.map(s => [s.id, s.scenario]));
const sitWhere = (what, f) => { const s = SIT.find(f); if (!s) throw new Error('selftest: no situation ' + what); return s.id; };
const DOCK = sitWhere('with the docking pose (POSE=S7POSE)', s => s.pose === 'S7POSE');
const DISC = sitWhere('body-centred (RECIPE BODYCTR)', s => s.recipe === 'BODYCTR');
const LUNAR = sitWhere('on the local vertical aimed at the Moon', s => s.recipe === 'LOCALVERT' && s.target === 'MOON');
const EARTHLV = sitWhere('on the local vertical aimed at the Earth', s => s.recipe === 'LOCALVERT' && s.target === 'EARTH');
const OTHER = sitWhere('of a second scenario', s => s.scenario !== SIT[0].scenario);
const maxdiff = (a, b) => a.reduce((m, v, i) => Math.max(m, Math.abs(v - b[i])), 0);
let ok = true;
for (const scene of SCENES) {
  const a = run(W, scene), b = run(F, scene);
  const t0 = performance.now(); for (let i = 0; i < 50; i++) W.view_frame();
  const ms = (performance.now() - t0) / 50;
  const same = a.nvec === b.nvec && a.nstar === b.nstar && a.nlab === b.nlab &&
               maxdiff(a.hdr, b.hdr) === 0 && maxdiff(a.vbuf, b.vbuf) === 0 &&
               a.ntxt === b.ntxt && maxdiff(a.tbuf, b.tbuf) === 0 &&
               a.tchr.join() === b.tchr.join();
  console.log(`scene ${scene}: GET ${a.hdr[0].toFixed(0)} s  vectors ${a.nvec}/${b.nvec}` +
    `  stars ${a.nstar}/${b.nstar}  labels ${a.nlab}/${b.nlab}  text ${a.ntxt}/${b.ntxt}` +
    `  ${same ? 'identical' : 'DIFFER'}  wasm ${ms.toFixed(2)} ms/frame`);
  if (!same || a.nvec === 0) ok = false;
}
// Views and camera targets (in_view, in_target): every scene external, and window views aimed at the
// Earth, the Moon, the Sun and the S-IVB; wasm and the fallback must agree.
if (W.in_view) {
  let same = true, n = 0;
  for (const scene of SCENES)
    for (const [v, t] of [[1, 0], [1, 4], [0, 1], [0, 2], [0, 3], [2, 0], [3, 0], [2, 1], [0, 6], [1, 6]]) {
      const a = run(W, scene, 3, v, t), b = run(F, scene, 3, v, t); n++;
      if (!(a.nvec === b.nvec && a.nstar === b.nstar && maxdiff(a.hdr, b.hdr) === 0 &&
            maxdiff(a.vbuf, b.vbuf) === 0)) same = false;
    }
  console.log(`views and targets: ${n} frames  ${same ? 'identical' : 'DIFFER'}`);
  if (!same) ok = false;
}
// Cabin interiors (in_flags bit 4): the CM and LM stations in every scene with and without the
// bit; wasm and the fallback must agree, and the bit must add lines where a station is drawn.
if (W.in_view) {
  let same = true, n = 0, more = 0;
  for (const scene of SCENES)
    for (const v of [2, 3]) {
      const off = run(W, scene, 3, v, 0), a = run(W, scene, 3 | 16, v, 0), b = run(F, scene, 3 | 16, v, 0); n++;
      if (!(a.nvec === b.nvec && maxdiff(a.hdr, b.hdr) === 0 && maxdiff(a.vbuf, b.vbuf) === 0)) same = false;
      if (a.nvec > off.nvec) more++;
    }
  console.log(`cabins: ${n} frames  ${same ? 'identical' : 'DIFFER'}  ${more} with interior lines`);
  if (!same || more === 0) ok = false;
}
// Window mask (in_flags bit 5): with the cabin (bit 4) in the CM and LM stations, the outside only
// through the windows. Wasm and the fallback must agree; bit 5 without bit 4 changes nothing; a
// masked frame never has more vectors, stars or labels than the unmasked one, and some have fewer.
// The docking situation's CM station looks along +X at the LM, where the CM has no window:
// unmasked, the LM's lines cross the middle of the frame; masked, the only line there is the
// X-axis mark (CMCAB, about 1 deg from the centre).
if (W.in_view) {
  let same = true, inert = true, fewer = 0, n = 0, never = true;
  for (const scene of SCENES)
    for (const v of [2, 3]) {
      const u = run(W, scene, 3 | 16, v, 0, 3), a = run(W, scene, 3 | 16 | 32, v, 0, 3), b = run(F, scene, 3 | 16 | 32, v, 0, 3); n++;
      if (!(a.nvec === b.nvec && a.nstar === b.nstar && a.nlab === b.nlab && maxdiff(a.vbuf, b.vbuf) === 0 &&
            maxdiff(a.lbuf, b.lbuf) === 0 && maxdiff(a.tbuf, b.tbuf) === 0)) same = false;
      const o = run(W, scene, 3, v, 0, 3), o5 = run(W, scene, 3 | 32, v, 0, 3);
      if (!(o.nvec === o5.nvec && o.nstar === o5.nstar && maxdiff(o.vbuf, o5.vbuf) === 0)) inert = false;
      if (a.nvec > u.nvec || a.nstar > u.nstar || a.nlab > u.nlab) never = false;
      if (a.nvec < u.nvec) fewer++;
    }
  // Lines with a point within 3 deg of the centre (ends and midpoint), and their largest reach.
  const mid = r => { let c = 0, far = 0; for (let i = 0; i < r.nvec; i++) {
    const p = r.vbuf.slice(5 * i, 5 * i + 4), q = [[p[0], p[1]], [p[2], p[3]], [(p[0] + p[2]) / 2, (p[1] + p[3]) / 2]];
    if (q.some(([x, y]) => Math.hypot(x, y) < 3)) { c++; far = Math.max(far, ...q.map(([x, y]) => Math.hypot(x, y))); } }
    return [c, far]; };
  const [cu] = mid(run(W, DOCK, 1 | 16, 2)), [cm, fm] = mid(run(W, DOCK, 1 | 16 | 32, 2));
  const centre = cu > 20 && cm > 0 && fm < 1.2;
  console.log(`window mask: ${n} frames  ${same ? 'identical' : 'DIFFER'}  bit 5 alone ${inert ? 'inert' : 'CHANGES FRAMES'}` +
    `  ${fewer} with fewer vectors${never ? '' : '  MORE IN SOME'}  scene ${DOCK} centre: ${cu} lines unmasked, ${cm} masked` +
    ` (out to ${fm.toFixed(2)} deg)${centre ? '' : '  WRONG'}`);
  if (!same || !inert || !never || fewer === 0 || !centre) ok = false;
}
// Label levels (in_lablv 0-3) with vehicle labels, markers and the launch pad: every scene in
// its own view and external, plus frames where markers or the pad show (the Moon view in the LM's
// descent, Earthrise external on the Moon, the Earth limb over Florida, Apollo 8 in its ascent);
// wasm and the fallback must agree on vectors, labels and text.
if (W.in_lablv) {
  let same = true, n = 0, kinds = new Set();
  const cases = [];
  for (const scene of SCENES)
    for (const v of [0, 1]) for (const lv of [0, 1, 2, 3]) cases.push([scene, v, 0, lv, null]);
  for (const lv of [1, 2, 3])
    cases.push([DISC, 0, 0, lv, 369640], [LUNAR, 1, 2, lv, null], [EARTHLV, 0, 0, lv, 5800],
               [EARTHLV, 1, 1, lv, 1200], [OTHER, 1, 1, lv, 8000]);
  for (const [scene, v, t, lv, get] of cases) {
    const a = run(W, scene, 3, v, t, lv, get), b = run(F, scene, 3, v, t, lv, get); n++;
    for (let i = 0; i < a.nlab; i++) kinds.add(a.lbuf[4 * i + 2]);
    if (!(a.nvec === b.nvec && a.nlab === b.nlab && maxdiff(a.hdr, b.hdr) === 0 &&
          maxdiff(a.vbuf, b.vbuf) === 0 && maxdiff(a.lbuf, b.lbuf) === 0 && a.ntxt === b.ntxt &&
          maxdiff(a.tbuf, b.tbuf) === 0 && a.tchr.join() === b.tchr.join())) same = false;
  }
  // The new label kinds must actually occur: 8 vehicles, 9 the launch pad.
  const seen = kinds.has(8) && kinds.has(9);
  console.log(`label levels: ${n} frames  ${same ? 'identical' : 'DIFFER'}  vehicle and pad labels ${seen ? 'seen' : 'MISSING'}`);
  if (!same || !seen) ok = false;
}
// Every situation as its cards say: hdr(7) its id, hdr(1) its default g.e.t. where the cards fix
// it (an EVENT plus an offset, or a g.e.t.; not ERISE, which ERFIND computes), hdr(16) its
// scenario's epoch offset from scenario 1's; and the first again afterwards, unchanged by the
// scenarios after it.  Those expected values come from the same cards, so two facts are also held
// here as literals, independent of the cards: Apollo 8's epoch offset, -17,887,260 s (its range
// zero 1968-12-21 12:51:00 UTC, MR8 p. 2-1, less Apollo 11's; CLAUDE.md, hdr(16)), and its
// Earthrise photograph's g.e.t., 75:48:39.7 = 272,919.7 s (SVS 4129, the PHOTO event).
{
  const a = run(W, OTHER), b = run(F, OTHER);
  const good = Math.abs(a.hdr[15] + 17887260) < 0.1 && a.hdr[0] === 272919.7 && maxdiff(a.vbuf, b.vbuf) === 0;
  console.log(`Apollo 8 (scene ${OTHER}): g.e.t. ${a.hdr[0]} s, epoch offset ${a.hdr[15].toFixed(2)} s  ${good ? 'ok' : 'WRONG'}`);
  if (!good) ok = false;
}
{
  const bad = [];
  for (const s of [...SIT, SIT[0]]) {
    const a = run(W, s.id), b = run(F, s.id), ep = SCNS[s.scenario].epoch;
    if (!(a.hdr[6] === s.id && Math.abs(a.hdr[15] - ep) < 0.1 && (s.get === null || Math.abs(a.hdr[0] - s.get) < 1e-6) &&
          maxdiff(a.vbuf, b.vbuf) === 0 && a.nvec > 0)) bad.push(s.id);
  }
  console.log(`situations: ${SIT.length} as their cards say (default g.e.t., epoch offset)  ${bad.length ? 'WRONG: ' + bad.join(' ') : 'ok'}`);
  if (bad.length) ok = false;
}
// The playlist reels (#18; data/reels/*/run.scn, VIEW_NAMES.REELS): every shot's situation exists, and its g.e.t. at
// start and end lies inside that situation's scenario (from its first to its last TIMELINE row) and draws there (the
// kernel takes it as given: hdr(1) is that g.e.t., hdr(7) the situation). An ERISE shot's times are offsets from the
// kernel's Earthrise (out_terise, after view_init of its situation), as the player resolves them. Literals, so the
// check is not only the cards against themselves: the demo reel's Earthrise shot starts 30 s after the situation's own
// default (ERFIND's Earthrise less 60 s, as the kernel computes it) and the tour's at it, both to 1 ulp; and the demo's
// LM descent shot starts at 369,656 s (102:40:56, the film fit: 27 s = 369,676 s and 35 s = 369,840 s, extrapolated to
// 26 s).
{
  const bad = [], REELS = NAMES.REELS || {};
  const terise = sit => { W.view_init(sit); return W.out_terise ? f64(W, 'out_terise', 1)[0] : NaN; };
  const ulp = x => Math.abs(x) * Number.EPSILON;
  let n = 0;
  for (const [id, r] of Object.entries(REELS))
    r.shots.forEach((sh, k) => {
      const s = SIT.find(x => x.id === sh.sit), where = `${id} shot ${k + 1}`;
      if (!s) { bad.push(where + ' (no situation)'); return; }
      const ev = NAMES.TIMELINE[String(s.scenario)].events.map(e => e[0]);
      const base = sh.rule === 'ERISE' ? terise(sh.sit) : 0;
      const g = sh.get ? sh.get.map(x => base + x) : [sh.at - sh.tte[0][1], sh.at - sh.tte[sh.tte.length - 1][1]];
      for (const t of g) {
        const a = run(W, sh.sit, 3, sh.view, 0, 0, t); n++;
        if (!(t >= Math.min(...ev) && t <= Math.max(...ev) && a.hdr[0] === t && a.hdr[6] === sh.sit && a.nvec > 0))
          bad.push(`${where} (${sh.name}) at ${t} s`);
      }
    });
  const demo = (REELS.demo || { shots: [] }).shots;
  const lmd = demo.find(sh => (SIT.find(x => x.id === sh.sit) || {}).recipe === 'CREWSTN');
  for (const [id, after] of [['demo', 30], ['tour', 0]]) {
    const rise = ((REELS[id] || { shots: [] }).shots).find(sh => (SIT.find(x => x.id === sh.sit) || {}).get_rule === 'ERISE-60');
    const def = rise && run(W, rise.sit).init, start = rise && terise(rise.sit) + rise.get[0];
    if (!rise || !(Math.abs(start - (def + after)) <= ulp(start)))
      bad.push(`${id} Earthrise: start ${start} s, the situation's default ${def} s plus ${after}`);
  }
  if (!lmd || lmd.get[0] !== 369656) bad.push(`demo LM descent: start ${lmd && lmd.get[0]} s, not 369656`);
  console.log(`reels: ${Object.keys(REELS).length} (${Object.keys(REELS).join(', ')}), ${n} shot ends in their scenarios` +
    `  ${bad.length ? 'WRONG: ' + bad.join('; ') : 'ok'}`);
  if (bad.length || !REELS.demo) ok = false;
}
// Simulation mode: run the engine with delta correction on (1) and off (0), then draw every
// scene from the tape (in_flags bit 3) and check wasm and the fallback agree; also time sim_run.
if (W.sim_run) {
  for (const sf of [1, 0]) {
    let same = true, drawn = 0, ms = 0, last = 0;
    for (const scene of SCENES) {
      // The engine runs over the current scenario: once for each scenario, after its scene's view_init.
      if (SCN[scene] !== last) {
        last = SCN[scene]; W.view_init(scene); F.view_init(scene);
        const t0 = performance.now(); W.sim_run(sf); ms += performance.now() - t0; F.sim_run(sf);
      }
      const a = run(W, scene, 3 | 8), b = run(F, scene, 3 | 8);
      if (!(a.nvec === b.nvec && a.nstar === b.nstar && maxdiff(a.hdr, b.hdr) === 0 &&
            maxdiff(a.vbuf, b.vbuf) === 0)) same = false;
      if (a.hdr[16] > 0) drawn++;
    }
    console.log(`sim flags ${sf}: sim_run ${ms.toFixed(1)} ms (wasm, both scenarios)  scenes drawn from the tape ${drawn}` +
      `  ${same ? 'identical' : 'DIFFER'}`);
    if (!same || drawn === 0) ok = false;
  }
}
// The card reader (src/vdeck.f, #26): the decks of build/decks.txt (tools/gen_data.py's order)
// loaded through deck_card, each file ended by deck_file, fill the run tables word for word as
// BLOCK DATA does: the same hash total (deck_sum) in wasm, in the fallback, and in the native
// driver both from its BLOCK DATA (gfortran's constants) and through its own reader; and the same
// frames.  Then planted faults in a deck, each refused with its own deck error, and a refused
// deck leaving nothing behind for the next load.
if (W.deck_open) {
  const DECKS = fs.readFileSync(path.join(R, 'build/decks.txt'), 'utf8').split('\n').filter(Boolean);
  const EOF = '\u0000end of file';
  const LINES = DECKS.flatMap(p => [...fs.readFileSync(path.join(R, p), 'utf8').split('\n'), EOF]);
  const enc = new TextEncoder();
  const load = (K, lines) => {
    K.deck_open();
    for (const ln of lines) {
      if (ln === EOF) { K.deck_file(); continue; }
      const b = enc.encode(ln), card = new Int32Array(K.memory.buffer, K.in_card.value, 1024);
      for (let i = 0; i < Math.min(b.length, 1024); i++) card[i] = b[i];
      K.deck_card(b.length);
    }
    K.deck_close();
    return [i32(K, 'out_dkerr'), i32(K, 'out_dkcrd'), i32(K, 'out_dkwrn')];
  };
  const sum = K => { K.deck_sum(); return Array.from(new Int32Array(K.memory.buffer, K.out_dksum.value, 4)).join(' '); };
  const fresh = async () => (await WebAssembly.instantiate(mod, { env: imports })).exports;
  const B = await fresh(), D = await fresh();
  const sumBD = sum(B), errD = load(D, LINES), sumD = sum(D), errF = load(F, LINES), sumF = sum(F);
  let native = 'not built', nativeDeck = 'not built';
  if (fs.existsSync(path.join(R, 'build/viewsvg'))) {
    const { execFileSync } = await import('child_process');
    const nenv = { ...process.env, VIEW_DKSUM: '1' };
    delete nenv.VIEW_DECK;
    native = execFileSync(path.join(R, 'build/viewsvg'), { env: nenv }).toString().trim();
    nativeDeck = execFileSync(path.join(R, 'build/viewsvg'), { cwd: R,
      env: { ...nenv, VIEW_DECK: DECKS.join(':') } }).toString().trim();
  }
  let same = true, frames = 0;
  for (const scene of SCENES) {
    for (const [fl, v] of [[3, 0], [3, 1], [3 | 4 | 16 | 32, 2]]) {
      const a = run(B, scene, fl, v, 0, 1), b = run(D, scene, fl, v, 0, 1);
      frames++;
      if (!(a.nvec === b.nvec && a.nstar === b.nstar && a.nlab === b.nlab && maxdiff(a.hdr, b.hdr) === 0 &&
            maxdiff(a.vbuf, b.vbuf) === 0 && maxdiff(a.lbuf, b.lbuf) === 0 && a.tchr.join() === b.tchr.join())) same = false;
    }
  }
  let last = 0;
  for (const scene of SCENES) {
    if (SCN[scene] === last) continue;
    last = SCN[scene];
    B.view_init(scene); D.view_init(scene); B.sim_run(1); D.sim_run(1);
    const a = run(B, scene, 3 | 8), b = run(D, scene, 3 | 8);
    frames++;
    if (!(a.nvec === b.nvec && maxdiff(a.hdr, b.hdr) === 0 && maxdiff(a.vbuf, b.vbuf) === 0)) same = false;
  }
  const good = errD[0] === 0 && errF[0] === 0 && sumD === sumBD && sumF === sumBD &&
               (native === 'not built' || (native === sumBD && nativeDeck === sumBD));
  console.log(`card reader: ${DECKS.length} decks, ${LINES.length - DECKS.length} lines, ${errD[2]} skipped; hash total ${sumD}` +
    ` (BLOCK DATA ${sumBD}, fallback ${sumF}, native BLOCK DATA ${native}, native reader ${nativeDeck})` +
    `  ${good ? 'equal' : 'DIFFER, deck error ' + errD}` +
    `  ${frames} frames ${same ? 'identical' : 'DIFFER'}`);
  if (!good || !same) ok = false;
  // Planted faults: [what, expected deck error, the deck's lines].
  const at = (re, f) => { const i = LINES.findIndex(l => re.test(l)); return LINES.map((l, j) => j === i ? f(l) : l); };
  const tl = LINES.find(l => l.startsWith('TIMELINE ')), lastEOF = LINES.length - 1;
  const without = re => LINES.filter(l => !re.test(l));
  const a8sit = LINES.findIndex(l => /^SITUATION ID=9 /.test(l));
  const cases = [
    ['a card of 1100 codes', 1, at(/^EVENT /, l => l + ' SRC="' + 'x'.repeat(1100) + '"')],
    ['a number with two points', 2, at(/^EVENT /, l => l.replace(/ T=\S+/, ' T=1.2.3'))],
    ['sixteen digits', 3, at(/^EPOCH /, l => l.replace(/JD=\S+/, 'JD=2440419.063889000'))],
    ['an unknown event kind', 4, at(/^EVENT /, l => l.replace(/KIND=\S+/, 'KIND=NOPE'))],
    ['an EVENT without T=', 5, at(/^EVENT /, l => l.replace(/ T=\S+/, ''))],
    ['a ROW outside a TABLE leg', 6, at(/^EVENT /, l => l + '\nROW T=1 LAT=0 LON=0 ALT=0 V=0 FPA=0 HDG=0').flatMap(l => l.split('\n'))],
    ['a scenario ID past the table', 7, at(/^SCENARIO /, l => l.replace(/ID=\S+/, 'ID=99'))],
    ['a situation ID given twice', 8, at(/^SITUATION ID=2 /, l => l.replace('ID=2', 'ID=1'))],
    ['TABLE rows out of order', 9, at(/^ROW /, l => l.replace(/ T=\S+/, ' T=999:00:00'))],
    ['a burn cue naming no row', 10, at(/^BURNCUE /, l => l.replace(/IGN="[^"]*"/, 'IGN="NO SUCH ROW"'))],
    ['the timeline over its maximum', 16, [...LINES.slice(0, lastEOF), ...Array(1500).fill(tl), EOF]],
    ['a situation ID past a gap', 20, at(/^SITUATION ID=9 /, l => l.replace('ID=9', 'ID=12'))],
    ['an open quote', 21, at(/^TIMELINE /, l => l + ' "')],
    ['a word without =', 21, at(/^EVENT /, l => l + ' LOOSE')],
    ['a layer named twice', 22, at(/^SITUATION /, l => l.replace(/LAYERS=(\w+)/, 'LAYERS=$1,$1'))],
    ['a pad name of eight characters', 23, at(/^PAD /, l => l.replace(/NAME=\S+/, 'NAME=LC-39A12'))],
    ['a second, different SITE NAME', 23, at(/^EPOCH /, l => l + '\nSITE NAME="OTHER" LAT=0 LON=0 AZ=0').flatMap(l => l.split('\n'))],
    ['no situation', 24, without(/^(SITUATION|RECIPE|VIEWS|HDRREF) /)],
    ['EPOCH before MISSION', 25, at(/^MISSION /, l => 'EPOCH JD=1\n' + l).flatMap(l => l.split('\n'))],
    ['a scenario without legs', 26, without(/^(LEG|ROW) /)],
    ['a GET= event the scenario lacks', 27, LINES.map((l, j) => j === a8sit ? l.replace(/GET=\S+/, 'GET=SLING+10') : l)],
    ['a scenario file without its SCENARIO card', 6, LINES.filter((l, j) => j !== LINES.findLastIndex(x => x.startsWith('SCENARIO ')))],
  ];
  const wrong = [];
  for (const [what, want, lines] of cases) {
    const K = await fresh(), [e, c] = load(K, lines);
    if (e !== want || i32(K, 'out_dkerr') !== want) wrong.push(`${what}: deck error ${e} at card ${c}, not ${want}`);
  }
  // A refused deck leaves the tables empty and draws nothing; the next good deck loads clean.
  const K = await fresh(), [e1] = load(K, cases[0][2]);
  K.view_init(1); K.view_frame();
  const empty = i32(K, 'nvec') === 0 && i32(K, 'nstar') === 0;
  const [e2] = load(K, LINES), again = sum(K);
  if (!(e1 !== 0 && empty && e2 === 0 && again === sumBD))
    wrong.push(`a refused deck, then a good one: errors ${e1}, ${e2}, empty frame ${empty}, hash ${again}`);
  // view_frame straight after a reload, without view_init: nothing from the last deck's situation.
  K.view_init(1); K.view_frame();
  load(K, cases[0][2]); K.view_frame();
  const emptyAfter = i32(K, 'nvec') === 0;
  load(K, LINES); K.view_frame();
  if (!(emptyAfter && i32(K, 'nvec') > 0))
    wrong.push(`view_frame after a reload without view_init: empty ${emptyAfter}, then ${i32(K, 'nvec')} vectors`);
  console.log(`deck errors: ${cases.length} planted faults, then a good deck after a refused one` +
    `  ${wrong.length ? 'WRONG: ' + wrong.join('; ') : 'each refused, reload clean'}`);
  if (wrong.length) ok = false;
}
console.log(ok ? 'PASS' : 'FAIL'); process.exit(ok ? 0 : 1);
