C     Generated by tools/gen_data.py from the SITUATION cards of
C     data/missions/*/*.scn.  Do not edit.  Layout: viewsit.inc.
C     RESTOMOD BEGIN: file INCLUDE (FORTRAN V's named PDP elements);
C     the 1108 loader skips unreferenced BLOCK DATA (docs/univac-1108.md).
      BLOCK DATA VIEWSB
      INCLUDE 'viewsit.inc'
C     SITUATION 1 (scenario 1)
C       EARTHRISE, recipe LOCALVERT: the film's first shot (t04.png);
C       time and field ours
      DATA SISN(1), SIGK(1), SIGE(1), SIFK(1), SIWN(1), SIPS(1) / 1, 3,
     & 0, 1, 1, 0 /
      DATA SIDW(1), SIRC(1), SIBD(1), SIMD(1), SIAZ(1), SITR(1) / 0, 1,
     & 2, 1, 1, 0 /
      DATA SIFB(1), SIAT(1), SIFE(1), SIVH(1), SIVW(1), SITG(1) / 0, 0,
     & 0, 0, 0, 2 /
      DATA SITF(1), SIRD(1), SICM(1), SILM(1), SIFX(1), SIXO(1) / 0, 1,
     & 2, 1, 0, 0 /
      DATA SIHK(1), SIGT(1), SIFV(1), SIEL(1), SIFL(1), SIFT(1) / 0,
     & -60.0D0, 8.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIDT(1), SIEO(1), SIAL(1), SIDS(1), SIHO(1), SIHR(1) / 0.0D0,
     & 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SILK(1,1), SILK(2,1), SILK(3,1), SITN(1,1), SITN(2,1),
     & SITN(3,1) / 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIXY(1,1), SIXY(2,1), SILY(1,1), SILY(2,1), SILY(3,1),
     & SILY(4,1) / 0.0D0, 0.0D0, 1, 2, 3, 4 /
      DATA SILY(5,1), SILY(6,1), SILY(7,1), SILY(8,1), SILY(9,1),
     & SILY(10,1) / 5, 6, 10, 0, 0, 0 /
      DATA SILY(11,1), SILY(12,1) / 0, 0 /
C     SITUATION 2 (scenario 1)
C       EARTH APPROACH, recipe INERTIAL: the film's second shot
C       (t08.png to t20.png); times and field ours
      DATA SISN(2), SIGK(2), SIGE(2), SIFK(2), SIWN(2), SIPS(2) / 1, 2,
     & 7, 1, 1, 0 /
      DATA SIDW(2), SIRC(2), SIBD(2), SIMD(2), SIAZ(2), SITR(2) / 0, 2,
     & 1, 0, 0, 0 /
      DATA SIFB(2), SIAT(2), SIFE(2), SIVH(2), SIVW(2), SITG(2) / 0, 1,
     & 7, 0, 0, 1 /
      DATA SITF(2), SIRD(2), SICM(2), SILM(2), SIFX(2), SIXO(2) / 0, 1,
     & 2, 1, 0, 0 /
      DATA SIHK(2), SIGT(2), SIFV(2), SIEL(2), SIFL(2), SIFT(2) / 0,
     & -18000.0D0, 60.0D0, 0.0D0, 0.0D0, 36000.0D0 /
      DATA SIDT(2), SIEO(2), SIAL(2), SIDS(2), SIHO(2), SIHR(2) /
     & 3600.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SILK(1,2), SILK(2,2), SILK(3,2), SITN(1,2), SITN(2,2),
     & SITN(3,2) / 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIXY(1,2), SIXY(2,2), SILY(1,2), SILY(2,2), SILY(3,2),
     & SILY(4,2) / 0.0D0, 0.0D0, 1, 2, 3, 4 /
      DATA SILY(5,2), SILY(6,2), SILY(7,2), SILY(8,2), SILY(9,2),
     & SILY(10,2) / 5, 6, 10, 0, 0, 0 /
      DATA SILY(11,2), SILY(12,2) / 0, 0 /
C     SITUATION 3 (scenario 1)
C       EARTH LIMB, recipe LOCALVERT: ours
      DATA SISN(3), SIGK(3), SIGE(3), SIFK(3), SIWN(3), SIPS(3) / 1, 1,
     & 0, 1, 1, 0 /
      DATA SIDW(3), SIRC(3), SIBD(3), SIMD(3), SIAZ(3), SITR(3) / 1, 1,
     & 1, 1, 0, 0 /
      DATA SIFB(3), SIAT(3), SIFE(3), SIVH(3), SIVW(3), SITG(3) / 0, 0,
     & 0, 0, 0, 1 /
      DATA SITF(3), SIRD(3), SICM(3), SILM(3), SIFX(3), SIXO(3) / 0, 1,
     & 2, 1, 0, 0 /
      DATA SIHK(3), SIGT(3), SIFV(3), SIEL(3), SIFL(3), SIFT(3) / 0,
     & 5400.0D0, 70.0D0, 8.0D0, 0.0D0, 0.0D0 /
      DATA SIDT(3), SIEO(3), SIAL(3), SIDS(3), SIHO(3), SIHR(3) / 0.0D0,
     & 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SILK(1,3), SILK(2,3), SILK(3,3), SITN(1,3), SITN(2,3),
     & SITN(3,3) / 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIXY(1,3), SIXY(2,3), SILY(1,3), SILY(2,3), SILY(3,3),
     & SILY(4,3) / 0.0D0, 0.0D0, 1, 2, 3, 4 /
      DATA SILY(5,3), SILY(6,3), SILY(7,3), SILY(8,3), SILY(9,3),
     & SILY(10,3) / 5, 6, 10, 0, 0, 0 /
      DATA SILY(11,3), SILY(12,3) / 0, 0 /
C     SITUATION 4 (scenario 1)
C       LM RENDEZVOUS, recipe LOCALVERT: the film's third shot
C       (t22.png, t25.png); time and field ours
C       HDRREF: ours
      DATA SISN(4), SIGK(4), SIGE(4), SIFK(4), SIWN(4), SIPS(4) / 1, 2,
     & 5, 1, 1, 1 /
      DATA SIDW(4), SIRC(4), SIBD(4), SIMD(4), SIAZ(4), SITR(4) / 0, 1,
     & 2, 2, 0, 0 /
      DATA SIFB(4), SIAT(4), SIFE(4), SIVH(4), SIVW(4), SITG(4) / 0, 0,
     & 0, 0, 0, 5 /
      DATA SITF(4), SIRD(4), SICM(4), SILM(4), SIFX(4), SIXO(4) / 0, 1,
     & 2, 1, 0, 0 /
      DATA SIHK(4), SIGT(4), SIFV(4), SIEL(4), SIFL(4), SIFT(4) / 1,
     & 120.0D0, 12.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIDT(4), SIEO(4), SIAL(4), SIDS(4), SIHO(4), SIHR(4) / 0.0D0,
     & 0.0D0, 0.0D0, 0.0D0, 0.0D0, 4.5D-3 /
      DATA SILK(1,4), SILK(2,4), SILK(3,4), SITN(1,4), SITN(2,4),
     & SITN(3,4) / 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIXY(1,4), SIXY(2,4), SILY(1,4), SILY(2,4), SILY(3,4),
     & SILY(4,4) / 0.0D0, 0.0D0, 1, 3, 4, 5 /
      DATA SILY(5,4), SILY(6,4), SILY(7,4), SILY(8,4), SILY(9,4),
     & SILY(10,4) / 6, 10, 0, 0, 0, 0 /
      DATA SILY(11,4), SILY(12,4) / 0, 0 /
C     SITUATION 5 (scenario 1)
C       LM DESCENT, recipe CREWSTN: the film's fourth shot (t28.png,
C       t31.png, t35.png); time ours
C       RECIPE: LPDDN fitted to the film's LPD marks (llpd.f)
      DATA SISN(5), SIGK(5), SIGE(5), SIFK(5), SIWN(5), SIPS(5) / 1, 1,
     & 0, 1, 2, 0 /
      DATA SIDW(5), SIRC(5), SIBD(5), SIMD(5), SIAZ(5), SITR(5) / 0, 3,
     & 2, 0, 0, 0 /
      DATA SIFB(5), SIAT(5), SIFE(5), SIVH(5), SIVW(5), SITG(5) / 0, 0,
     & 0, 2, 0, 2 /
      DATA SITF(5), SIRD(5), SICM(5), SILM(5), SIFX(5), SIXO(5) / 0, 2,
     & 0, 2, 0, 0 /
      DATA SIHK(5), SIGT(5), SIFV(5), SIEL(5), SIFL(5), SIFT(5) / 0,
     & 369720.0D0, 82.4D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIDT(5), SIEO(5), SIAL(5), SIDS(5), SIHO(5), SIHR(5) / 0.0D0,
     & 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SILK(1,5), SILK(2,5), SILK(3,5), SITN(1,5), SITN(2,5),
     & SITN(3,5) / 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIXY(1,5), SIXY(2,5), SILY(1,5), SILY(2,5), SILY(3,5),
     & SILY(4,5) / 0.0D0, 0.0D0, 1, 2, 3, 4 /
      DATA SILY(5,5), SILY(6,5), SILY(7,5), SILY(8,5), SILY(9,5),
     & SILY(10,5) / 5, 6, 10, 8, 9, 0 /
      DATA SILY(11,5), SILY(12,5) / 0, 0 /
C     SITUATION 6 (scenario 1)
C       MOON VIEW, recipe BODYCTR: ours, a modern addition
      DATA SISN(6), SIGK(6), SIGE(6), SIFK(6), SIWN(6), SIPS(6) / 1, 2,
     & 6, 2, 1, 0 /
      DATA SIDW(6), SIRC(6), SIBD(6), SIMD(6), SIAZ(6), SITR(6) / 6, 4,
     & 2, 0, 0, 0 /
      DATA SIFB(6), SIAT(6), SIFE(6), SIVH(6), SIVW(6), SITG(6) / 0, 0,
     & 0, 0, 0, 2 /
      DATA SITF(6), SIRD(6), SICM(6), SILM(6), SIFX(6), SIXO(6) / 0, 0,
     & 0, 0, 1, 0 /
      DATA SIHK(6), SIGT(6), SIFV(6), SIEL(6), SIFL(6), SIFT(6) / 0,
     & 0.0D0, 0.85D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIDT(6), SIEO(6), SIAL(6), SIDS(6), SIHO(6), SIHR(6) / 0.0D0,
     & 0.0D0, 35000.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SILK(1,6), SILK(2,6), SILK(3,6), SITN(1,6), SITN(2,6),
     & SITN(3,6) / 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIXY(1,6), SIXY(2,6), SILY(1,6), SILY(2,6), SILY(3,6),
     & SILY(4,6) / 0.0D0, 0.0D0, 1, 2, 3, 4 /
      DATA SILY(5,6), SILY(6,6), SILY(7,6), SILY(8,6), SILY(9,6),
     & SILY(10,6) / 5, 6, 0, 0, 0, 0 /
      DATA SILY(11,6), SILY(12,6) / 0, 0 /
C     SITUATION 7 (scenario 1)
C       TRANSPOSITION AND DOCKING, recipe INERTIAL: Mission Report
C       MSC-00171 p. 4-2 and table 7-II p. 7-9 (see S7POSE); moment and
C       field ours
C       HDRREF: Apollo 11 press kit, printed p. 96 (the LM's width);
C       the offset ours
      DATA SISN(7), SIGK(7), SIGE(7), SIFK(7), SIWN(7), SIPS(7) / 1, 2,
     & 3, 1, 1, 2 /
      DATA SIDW(7), SIRC(7), SIBD(7), SIMD(7), SIAZ(7), SITR(7) / 0, 2,
     & 0, 0, 0, 0 /
      DATA SIFB(7), SIAT(7), SIFE(7), SIVH(7), SIVW(7), SITG(7) / 0, 2,
     & 0, 0, 0, 5 /
      DATA SITF(7), SIRD(7), SICM(7), SILM(7), SIFX(7), SIXO(7) / 0, 1,
     & 2, 1, 0, 1 /
      DATA SIHK(7), SIGT(7), SIFV(7), SIEL(7), SIFL(7), SIFT(7) / 2,
     & 60.0D0, 30.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIDT(7), SIEO(7), SIAL(7), SIDS(7), SIHO(7), SIHR(7) / 0.0D0,
     & 0.0D0, 0.0D0, 0.0D0, 0.72D-3, 2.15D-3 /
      DATA SILK(1,7), SILK(2,7), SILK(3,7), SITN(1,7), SITN(2,7),
     & SITN(3,7) / 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIXY(1,7), SIXY(2,7), SILY(1,7), SILY(2,7), SILY(3,7),
     & SILY(4,7) / 60.0D0, 25.0D0, 1, 2, 3, 4 /
      DATA SILY(5,7), SILY(6,7), SILY(7,7), SILY(8,7), SILY(9,7),
     & SILY(10,7) / 5, 6, 10, 7, 0, 0 /
      DATA SILY(11,7), SILY(12,7) / 0, 0 /
C     SITUATION 8 (scenario 1)
C       DOCKED STACK, recipe EXTSEED: Apollo 11 Flight Journal
C       010:58:19 (PTC); moment, distance and field ours
C       HDRREF: ours
      DATA SISN(8), SIGK(8), SIGE(8), SIFK(8), SIWN(8), SIPS(8) / 1, 2,
     & 8, 1, 1, 3 /
      DATA SIDW(8), SIRC(8), SIBD(8), SIMD(8), SIAZ(8), SITR(8) / 0, 5,
     & 1, 0, 0, 0 /
      DATA SIFB(8), SIAT(8), SIFE(8), SIVH(8), SIVW(8), SITG(8) / 0, 3,
     & 0, 0, 1, 4 /
      DATA SITF(8), SIRD(8), SICM(8), SILM(8), SIFX(8), SIXO(8) / 0, 0,
     & 2, 1, 0, 0 /
      DATA SIHK(8), SIGT(8), SIFV(8), SIEL(8), SIFL(8), SIFT(8) / 3,
     & 1800.0D0, 40.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIDT(8), SIEO(8), SIAL(8), SIDS(8), SIHO(8), SIHR(8) / 0.0D0,
     & 0.0D0, 0.0D0, 0.060D0, 2.743D-3, 1.0D-2 /
      DATA SILK(1,8), SILK(2,8), SILK(3,8), SITN(1,8), SITN(2,8),
     & SITN(3,8) / 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SIXY(1,8), SIXY(2,8), SILY(1,8), SILY(2,8), SILY(3,8),
     & SILY(4,8) / 0.0D0, 0.0D0, 1, 2, 3, 4 /
      DATA SILY(5,8), SILY(6,8), SILY(7,8), SILY(8,8), SILY(9,8),
     & SILY(10,8) / 5, 6, 10, 0, 0, 0 /
      DATA SILY(11,8), SILY(12,8) / 0, 0 /
C     SITUATION 9 (scenario 2)
C       APOLLO 8 EARTHRISE, recipe LOCALVERT: SVS 4129 (AS08-14-2383 at
C       75:48:39.7); Apollo 8 Flight Journal day 4 orbit 4 (250 mm
C       lens); the gate measured by us
C       RECIPE: TURN fitted by us to the ASU scan of AS08-14-2383;
C       OFFLEG ours
      DATA SISN(9), SIGK(9), SIGE(9), SIFK(9), SIWN(9), SIPS(9) / 2, 2,
     & 12, 1, 1, 0 /
      DATA SIDW(9), SIRC(9), SIBD(9), SIMD(9), SIAZ(9), SITR(9) / 0, 1,
     & 2, 1, 1, 1 /
      DATA SIFB(9), SIAT(9), SIFE(9), SIVH(9), SIVW(9), SITG(9) / 1, 0,
     & 0, 0, 0, 2 /
      DATA SITF(9), SIRD(9), SICM(9), SILM(9), SIFX(9), SIXO(9) / 1, 1,
     & 2, 1, 0, 0 /
      DATA SIHK(9), SIGT(9), SIFV(9), SIEL(9), SIFL(9), SIFT(9) / 0,
     & 0.0D0, 12.72D0, 0.0D0, 8.0D0, 0.0D0 /
      DATA SIDT(9), SIEO(9), SIAL(9), SIDS(9), SIHO(9), SIHR(9) / 0.0D0,
     & 0.0D0, 0.0D0, 0.0D0, 0.0D0, 0.0D0 /
      DATA SILK(1,9), SILK(2,9), SILK(3,9), SITN(1,9), SITN(2,9),
     & SITN(3,9) / 0.0D0, 0.0D0, 0.0D0, -0.9043D0, 3.7599D0, -6.7873D0 /
      DATA SIXY(1,9), SIXY(2,9), SILY(1,9), SILY(2,9), SILY(3,9),
     & SILY(4,9) / 0.0D0, 0.0D0, 1, 2, 3, 4 /
      DATA SILY(5,9), SILY(6,9), SILY(7,9), SILY(8,9), SILY(9,9),
     & SILY(10,9) / 5, 6, 10, 0, 0, 0 /
      DATA SILY(11,9), SILY(12,9) / 0, 0 /
      END
C     RESTOMOD END
